
name: Build and Deploy Docker Image

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64,arm'
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerRegistry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/bbzblit/m293-project/app:latest --push .
